# sort list of cars in alphabetically
cars = ['bmw', 'audi', 'toyota', 'subaru']
cars.sort()
print(cars)
print()
# sort list in alphabetically in the reverse way
cars.sort(reverse = True)
print(cars)
print()
cars = ['bmw', 'audi', 'toyota', 'subaru']
print('here is the actual lis:\n', cars)
print()
print('here is the sorted list\n', sorted(cars))
print()
print('here is the original list again\n', cars)
print('here is the reverse list')
cars.reverse()
print(cars)
print()
cars.reverse()
print(cars)
print()

places = ['America', 'New York', 'Swizerland', 'Canada', 'Peris']
print('original list:')
print(places)
print()
print('sorted list:')
print(sorted(places))
print()
print('oroginal list:')
print(places)
print()
print('sorted reverse by alphabetically')
print(sorted(places, reverse = True))
print()
print('original list again:')
print(places)
print()
print('reverse list:')
places.reverse()
print(places)
print()
print('original list:')
places.reverse()
print(places)
print()
print('sort in alphabetical order:')
places.sort()
print(places)
print()
print('reverse alphabetical')
places.sort(reverse = True)
print(places)

#error
names = ['salma', 'shema', 'sakiba', 'sagor']
print(names[3])
print()
print(names[-1])
print()
names = []
print(names[-1]) # it's not working so it displayed error
